import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useEffect, useCallback, useState, useReducer } from 'react';
import Posts from '../src/components/Posts';

const initialState = {
  posts: [],
  isLoading: false,
  error: '',
};

export default function Home({ foo }) {
  const reducer = (state, action) => {
    switch (action.type) {
      case 'start':
        return {
          ...state,
          isLoading: true,
        };
      case 'end':
        return {
          ...state,
          isLoading: false,
          posts: action.posts,
        };
      case 'error':
        return {
          ...state,
          isLoading: false,
          error: action.error,
        };

      default:
        break;
    }
  };
  const [state, dispatch] = useReducer(reducer, initialState);
  return (
    <div className={styles.container}>
      <Head>
        <title>CRA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Posts {...{ state, dispatch }} />

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
